# Generated by Django 2.2.5 on 2019-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190912_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movieinks',
            new_name='MovieLinks',
        ),
        migrations.AlterModelOptions(
            name='movielinks',
            options={'verbose_name': 'Movie Links', 'verbose_name_plural': 'Movie Links'},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
