# Generated by Django 2.2.5 on 2019-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('NR', 'Not Rated'), ('G', 'General Audiences'), ('PG', 'Parental Audiences'), ('R', 'Restricted')], max_length=2),
        ),
    ]
